allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@6.4.5 || 7.0.2 || 7.2.2
  - '@astrojs/starlight@0.40.0 || 0.41.0'
  - '@expressive-code/*'
  - astro-expressive-code@0.43.1
  - expressive-code@0.43.1
  - rehype-expressive-code@0.43.1
  - '@astrojs/markdown-satteri@0.3.0 || 0.3.2'
  - starlight-giscus@1.1.0
  - '@alpinejs/*'
  - alpinejs@3.16.0
